### ISSUE TITLE
Cached results (huge performance enhancement)

### ISSUE THREAD

**Issue by EFHIII** [Prisoners-Dilemma-Enjoyers/PrisonersDilemmaTournament#9]
Cache results into a cache file, and when running a match, unless a flag is provided to ignore the cache, check if the two opponents have a match cached. 

To make sure the cache isn't being used when code, store a hash (MD5 for example) for the code of each strategy's .py file and if it changes, it gets a new entry. 

Would also maybe want a flag that clears the cache, though that could be done manually fairly easily by deleting the cache file.

This would make it so that when changing code, you're only running `number of players * runs per pairing` instead of number of `players/2*(number of players-1) * runs per pairing`

Cache file can probably be JSON. That'd make it easy to then analyze with new scripts down the line.

**Comment by dosu0** [comment]
Yea I'm working on this  [here](https://github.com/Platinum-Phoenix/PrisonersDilemmaTournament/tree/caching).

**Comment by EFHIII** [comment]
## Some thoughts regarding even more performance enhancements:

For matches between two strategies that don't use random, repeated matches will always have the same outcome, so you could try, for example, running matches 10 times, and if the first 200 moves are the same for both players all 10 times, you can take the average from just those 10, otherwise you know RNG played a part and you can then repeat 990 more times.

This would significantly reduce the time it takes to run without significantly changing the results compared to running it 1000 times.

There are a few exceptions where strategies using RNG could falsely be flagged as not using RNG using the above, for example, strategies that only use RNG after the 200th move or strategies that have a small chance of RNG of changing things; maybe 0.05% of the time, they defect on the 1st move or something.

Another method you could use is checking of the source code includes the word "random" since they're probably not using RNG if they don't include random. This would instead have false positives instead of false negatives, which might be preferred. It's still probably a good idea to run matches not using RNG a few times since the match length is random, and that can effect the score. The difference that makes compared to other forms of RNG is probably going to be far less noticeable. Historically, a lot of strategies will cooperate until defected against, and in that situation, the score is 3 for both sides no matter how long the match is. If you want to be as cautious about that type of RNG as possible, you could check if across a few rounds the score for both stays within a small range (+/- 3% or so) and if it does, it's pretty safe to just average from there and move on.
